PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS Leases(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_name TEXT NOT NULL,
  unit_no TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT,
  monthly_rent REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS Charges(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lease_id INTEGER NOT NULL REFERENCES Leases(id) ON DELETE CASCADE,
  due_date TEXT NOT NULL,
  amount REAL NOT NULL,
  type TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Payments(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lease_id INTEGER NOT NULL REFERENCES Leases(id) ON DELETE CASCADE,
  paid_date TEXT NOT NULL,
  amount REAL NOT NULL,
  method TEXT
);


