CREATE TABLE Leases(
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  tenant_name VARCHAR2(120) NOT NULL,
  unit_no VARCHAR2(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  monthly_rent NUMBER(10,2) NOT NULL
);
CREATE TABLE Charges(
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  lease_id NUMBER NOT NULL REFERENCES Leases(id),
  due_date DATE NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  type VARCHAR2(30) NOT NULL
);
CREATE TABLE Payments(
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  lease_id NUMBER NOT NULL REFERENCES Leases(id),
  paid_date DATE NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  method VARCHAR2(30)
);
CREATE INDEX ix_charges_lease_due ON Charges(lease_id, due_date);
CREATE INDEX ix_payments_lease_paid ON Payments(lease_id, paid_date);


